#documentation profile detection and HTML content/navigation analysis

from __future__ import annotations

from bs4 import BeautifulSoup
from bs4 import NavigableString
from bs4 import Tag
from pathlib import Path
from typing import List
from typing import Optional
from typing import Sequence
from typing import Set
from typing import Tuple
from urllib.parse import unquote
from urllib.parse import urlsplit
import posixpath
import re

from .constants import (
    DOC_LIKE_KEYWORDS,
    DOC_PAGE_EXTENSIONS,
    GENERIC_BAD_LINK_TEXT_RE,
    GENERIC_CHROME_CLASS_RE,
    GENERIC_CONTENT_CLASS_RE,
    GENERIC_CONTENT_SELECTORS,
    GENERIC_DOC_LINK_TEXT_RE,
    GENERIC_NAV_SELECTORS,
    GENERIC_SKIP_PATH_TOKENS,
    GLOBAL_CHROME_RE,
    GLOBAL_NAV_TITLE_HINTS,
    PREFERRED_LANGUAGE_DEFAULT,
    PROFILE_HINTS,
    SIDEBAR_CONTEXT_RE,
    TOC_CONTEXT_RE,
)
from .text import (
    clean_text,
    dedupe_preserve_order,
)
from .urls import (
    ensure_trailing_slash,
    is_javadoc_url,
    is_probably_asset,
    language_matches_preference,
    normalize_url,
    path_similarity,
    query_looks_search_like,
    should_skip_crawl_url,
    split_and_normalize,
    urls_equivalent,
)


def detect_profile(soup: BeautifulSoup, url: str, hint: Optional[str] = None) -> str:

    if hint and hint != "generic":
        hard = detect_profile(soup, url, hint=None)
        if hard != "generic":
            return hard
        return hint

    html_tag = soup.find("html")
    html_classes = {cls.lower() for cls in (html_tag.get("class", []) if html_tag else [])}
    html_attrs = html_tag.attrs if html_tag else {}
    body_text = (soup.get_text(" ", strip=True)[:1000] if soup else "").lower()
    path = urlsplit(url).path.lower()

    if is_javadoc_url(url) or soup.select_one("body.class-declaration-page, body.package-declaration-page, .javadoc-content, .main-grid") or "generated by javadoc" in body_text:
        return "javadoc"
    if soup.select_one("main.article, article.doc, .nav-container, .nav-menu, .nav-panel-menu"):
        return "antora"
    if (
        soup.select_one("#toc.toc, #toc, .sect1, .sect2")
        and ("asciidoctor" in body_text or any("asciidoctor" in (meta.get("content") or "").lower() for meta in soup.find_all("meta")))
    ):
        return "asciidoctor"

    if soup.select_one("#__docusaurus, .theme-doc-markdown, .theme-doc-sidebar-container"):
        return "docusaurus"
    if (
        html_attrs.get("data-readthedocs-tool") == "sphinx"
        or "writer-html5" in html_classes
        or soup.select_one(".wy-menu.wy-menu-vertical, .rst-content, .bd-article, .bd-sidebar, nav.bd-links")
        or any(
            (meta.get("content") or "").lower().find("sphinx") >= 0
            for meta in soup.find_all("meta")
        )
    ):
        return "sphinx"
    if soup.select_one(".md-content__inner, nav[data-md-level], [data-md-component]"):
        return "mkdocs"
    if soup.select_one(".vp-doc, .VPSidebar, .VPSidebarNav, .VPDoc") or soup.select_one("script[src*='/assets/'][type='module']") and "vitepress" in body_text:
        return "vitepress"
    if soup.select_one("#bodyColumn, #navcolumn, #leftColumn") or "built by maven" in body_text:
        return "maven"
    if (
        soup.select_one(".book-menu, .book-page, .gitbook-navigation, .gitbook-page, .markdown-section, [data-testid='page.content'], [data-testid*='sidebar' i]")
        or any(
            "gitbook" in (meta.get("content") or "").lower()
            for meta in soup.find_all("meta")
        )
    ):
        return "book"
    return "generic"


def profile_selectors(profile: str, kind: str) -> List[str]:
    hints = PROFILE_HINTS.get(profile, {})
    selectors = list(hints.get(kind, []))
    selectors.extend(GENERIC_CONTENT_SELECTORS if kind == "content" else GENERIC_NAV_SELECTORS)
    return dedupe_preserve_order(selectors)


def select_content_root(soup: BeautifulSoup, profile: str = "generic") -> Optional[Tag]:
    if profile == "generic":
        generic_root = select_generic_content_root(soup)
        if generic_root is not None:
            return generic_root

    best: Tuple[int, int, Optional[Tag]] = (-10**9, -10**9, None)
    seen: Set[int] = set()

   
   
   
    preferred_selectors = PROFILE_HINTS.get(profile, {}).get("content", [])
    preferred: List[Tuple[int, int, Tag]] = []
    for rank, selector in enumerate(preferred_selectors):
        for node in soup.select(selector):
            if id(node) in seen:
                continue
            seen.add(id(node))
            score = compute_content_score(node)
            if score > -1500:
                preferred.append((score, -rank, node))
    if preferred:
        preferred.sort(key=lambda item: (item[0], item[1]), reverse=True)
        return preferred[0][2]

    selectors = profile_selectors(profile, "content")
    for rank, selector in enumerate(selectors):
        for node in soup.select(selector):
            if id(node) in seen:
                continue
            seen.add(id(node))
            score = compute_content_score(node)
            tie = -rank
            if score > best[0] or (score == best[0] and tie > best[1]):
                best = (score, tie, node)
    return best[2]


def compute_content_score(node: Tag) -> int:
    text_len = len(clean_text(node.get_text(" ", strip=True)))
    headings = len(node.find_all(re.compile(r"^h[1-6]$")))
    paragraphs = len(node.find_all("p"))
    code_blocks = len(node.find_all("pre"))
    tables = len(node.find_all("table"))
    lists = len(node.find_all(["ul", "ol", "dl"]))
    links = node.find_all("a", href=True)
    link_count = len(links)
    link_text_len = sum(len(clean_text(a.get_text(" ", strip=True))) for a in links)
    link_density = link_text_len / max(text_len, 1)

    attrs = " ".join([
        node.get("id", ""),
        *node.get("class", []),
        node.name or "",
    ]).lower()

    score = text_len
    score += headings * 300
    score += paragraphs * 70
    score += code_blocks * 180
    score += tables * 90
    score += lists * 25
    if node.name in {"main", "article"}:
        score += 400
    if re.search(
        r"content|article|main|markdown|doc|document|bodycolumn|page|prose|"
        r"rst-content|md-content|vp-doc|theme-doc",
        attrs,
    ):
        score += 1200
    if re.search(r"nav|sidebar|menu|header|footer|breadcrumb|toc|search|toolbar|topbar", attrs):
        score -= 1600
    score -= int(link_density * 900)

   
   
    if link_count > 40 and paragraphs < 3 and code_blocks == 0 and tables < 2:
        score -= 3000
    if text_len < 120:
        score -= 1200
    return score


def tag_depth(tag: Tag) -> int:
    depth = 0
    current = tag.parent
    while isinstance(current, Tag):
        depth += 1
        current = current.parent
    return depth


def direct_text_len(tag: Tag) -> int:
    pieces: List[str] = []
    for child in tag.children:
        if isinstance(child, NavigableString):
            pieces.append(str(child))
    return len(clean_text(" ".join(pieces)))


def is_generic_chrome_candidate(tag: Tag) -> bool:
    if tag.name in {"nav", "aside", "header", "footer", "form"}:
        return True
    role = str(tag.get("role", "")).lower()
    if role in {"navigation", "banner", "contentinfo", "search", "complementary"}:
        return True
    attrs = " ".join([
        tag.get("id", ""),
        *tag.get("class", []),
        tag.get("aria-label", ""),
        tag.name or "",
    ])
    return bool(GENERIC_CHROME_CLASS_RE.search(attrs))


def generic_content_candidate_score(node: Tag) -> int:
    text = clean_text(node.get_text(" ", strip=True))
    text_len = len(text)
    if text_len < 10:
        return -10**8

    links = node.find_all("a", href=True)
    link_text_len = sum(len(clean_text(a.get_text(" ", strip=True))) for a in links)
    link_density = link_text_len / max(text_len, 1)
    headings = len(node.find_all(re.compile(r"^h[1-6]$")))
    paragraphs = len(node.find_all("p"))
    code_blocks = len(node.find_all("pre"))
    tables = len(node.find_all("table"))
    list_count = len(node.find_all(["ul", "ol", "dl"]))

    attrs = " ".join([node.get("id", ""), *node.get("class", []), node.name or ""])
    score = compute_content_score(node)

   
    score += min(text_len, 12000)
    score += paragraphs * 160

    score += headings * 220
    score += code_blocks * 260
    score += tables * 120
    score += min(list_count, 20) * 35

    if node.name == "article":
        score += 2200
    elif node.name == "main":
        score += 1800
    elif str(node.get("role", "")).lower() == "main":
        score += 1600

    if GENERIC_CONTENT_CLASS_RE.search(attrs):
        if re.search(r"(?:^|[-_\s])(?:container|wrapper)(?:$|[-_\s])", attrs, re.I):
            score += 150
        else:
            score += 1000

    direct_chrome_children = 0
    for child in node.find_all(True, recursive=False):
        if isinstance(child, Tag) and is_generic_chrome_candidate(child):
            direct_chrome_children += 1
    score -= direct_chrome_children * 900

    if is_generic_chrome_candidate(node):
        score -= 3200
    try:
        if is_inside_global_chrome(node):
            score -= 2600
        if is_sidebarish_tag(node):
            score -= 2600
        if is_toc_like_tag(node):
            score -= 2200
    except Exception:
        pass

   
   
   
    score -= int(link_density * 2200)
    if len(links) > 35 and paragraphs < 4 and code_blocks == 0:
        score -= 4200
    if link_density > 0.55 and paragraphs < 5:
        score -= 3500

   
    score -= max(0, tag_depth(node) - 8) * 40
    return score


def iter_generic_content_candidates(soup: BeautifulSoup) -> List[Tag]:
    candidates: List[Tag] = []
    seen: Set[int] = set()

    selectors = [
        "main article", "article", "main", "[role='main']",
        "[itemprop='articleBody']", "[itemprop='text']",
        ".markdown-body", ".prose", ".post-content", ".entry-content",
        ".article-content", ".page-content", ".content-body", ".docs-content",
        ".doc-content", ".documentation-content", ".td-content", "article.doc",
        "main .doc", "[role='main'] .doc", ".documentation", ".manual", ".guide", ".chapter",
        "[class*='content' i]", "[id*='content' i]",
        "[class*='article' i]", "[id*='article' i]",
        "[class*='docs' i]", "[id*='docs' i]",
        "#main", "#content", "#contents", "#main-content", "#documentation",
    ]
    for selector in selectors:
        for node in soup.select(selector):
            if isinstance(node, Tag) and id(node) not in seen:
                seen.add(id(node))
                candidates.append(node)

   
   
    for node in soup.find_all(["main", "article", "section", "div", "td"], limit=2500):
        if not isinstance(node, Tag) or id(node) in seen:
            continue
        text_len = len(clean_text(node.get_text(" ", strip=True)))
        attrs = " ".join([node.get("id", ""), *node.get("class", []), node.name or ""])
        if node.name == "td":
            td_id = str(node.get("id", "")).lower()
            td_classes = " ".join(node.get("class", [])).lower()
            td_contentish = (
                td_id in {"bodycolumn", "content", "contentbox", "main", "body", "doc-content"}
                or GENERIC_CONTENT_CLASS_RE.search(attrs)
                or "main" in td_classes
                or len(node.find_all(re.compile(r"^h[1-6]$"))) >= 1
            )
            if not td_contentish and text_len < 500:
                continue
        min_text = 10 if GENERIC_CONTENT_CLASS_RE.search(attrs) or node.name in {"main", "article", "td"} else 160
        if text_len < min_text:
            continue
        if node.name not in {"main", "article"} and not GENERIC_CONTENT_CLASS_RE.search(attrs):
           
            if len(node.find_all("p")) < 2 and len(node.find_all(re.compile(r"^h[1-6]$"))) < 1 and len(node.find_all("pre")) < 1:
                continue
        if is_generic_chrome_candidate(node):
            continue
        seen.add(id(node))
        candidates.append(node)

    body = soup.body
    if body is not None and id(body) not in seen:
        candidates.append(body)

    return candidates


def tighten_generic_content_root(node: Tag, score: int) -> Tag:



    current = node
    current_score = score

    while True:
        best_child: Optional[Tag] = None
        best_score = -10**9
        for child in current.find_all(["main", "article", "section", "div", "td", "table", "tbody", "tr"], recursive=False):
            if not isinstance(child, Tag):
                continue
            child_score = generic_content_candidate_score(child)
            if child_score > best_score:
                best_score = child_score
                best_child = child

        if best_child is None:
            break

        current_text = len(clean_text(current.get_text(" ", strip=True)))
        child_text = len(clean_text(best_child.get_text(" ", strip=True)))
        if child_text <= 0:
            break

       
       
        if best_score >= current_score + 350 or (
            best_score >= int(current_score * 0.78)
            and child_text >= int(current_text * 0.45)
            and child_text < int(current_text * 0.92)
        ):
            current = best_child
            current_score = best_score
            continue
        break

    return current


def select_generic_content_root(soup: BeautifulSoup) -> Optional[Tag]:
    candidates = iter_generic_content_candidates(soup)
    if not candidates:
        return soup.find("main") or soup.find("article") or soup.body

    best_node: Optional[Tag] = None
    best_score = -10**9
    best_tie = -10**9

    for node in candidates:
        score = generic_content_candidate_score(node)
        text_len = len(clean_text(node.get_text(" ", strip=True)))
       
        tie = tag_depth(node) * 25 - text_len // 250
        if node.name in {"article", "main"}:
            tie += 500
        if score > best_score or (score == best_score and tie > best_tie):
            best_node = node
            best_score = score
            best_tie = tie

    if best_node is None or best_score < -2000:
        return soup.find("main") or soup.find("article") or soup.body

    return tighten_generic_content_root(best_node, best_score)


def tag_attr_signature(tag: Tag) -> str:
    attrs: List[str] = [tag.name or ""]
    for attr in ("id", "class", "role", "aria-label", "data-testid", "data-md-component"):
        value = tag.get(attr)
        if isinstance(value, list):
            attrs.extend(str(v) for v in value)
        elif value:
            attrs.append(str(value))
    return " ".join(attrs).lower()


def tag_context_signature(tag: Tag, max_ancestors: int = 5) -> str:
    pieces: List[str] = []
    current = tag
    steps = 0
    while isinstance(current, Tag) and steps <= max_ancestors:
        pieces.append(tag_attr_signature(current))
        parent = current.parent
        if not isinstance(parent, Tag):
            break
        current = parent
        steps += 1
    return " ".join(pieces).lower()


def is_inside_global_chrome(tag: Tag) -> bool:
    current = tag
    while isinstance(current, Tag):
        if current.name in {"header", "footer"}:
            return True
        role = str(current.get("role", "")).lower()
        if role in {"banner", "contentinfo"}:
            return True
        sig = tag_attr_signature(current)
        if GLOBAL_CHROME_RE.search(sig) and not SIDEBAR_CONTEXT_RE.search(sig):
            return True
        parent = current.parent
        if not isinstance(parent, Tag):
            break
        current = parent
    return False


def is_sidebarish_tag(tag: Tag) -> bool:
    if tag.name == "aside" and not is_inside_global_chrome(tag):
        return True
    sig = tag_context_signature(tag)
    return bool(SIDEBAR_CONTEXT_RE.search(sig)) and not is_inside_global_chrome(tag)


def is_toc_like_tag(tag: Tag) -> bool:
    sig = tag_context_signature(tag, max_ancestors=2)
    text = clean_text(tag.get_text(" ", strip=True)).lower()
    if TOC_CONTEXT_RE.search(sig):
        return True
    if "on this page" in text or "table of contents" in text or "page contents" in text:
        normal_links = 0
        fragment_links = 0
        for a in tag.select("a[href]"):
            href = (a.get("href") or "").strip()
            if href.startswith("#"):
                fragment_links += 1
            elif href:
                normal_links += 1
        return fragment_links >= max(3, normal_links * 2)
    return False


def has_structured_nav_headings(tag: Tag) -> bool:

    direct_lists = [child for child in tag.children if isinstance(child, Tag) and child.name in {"ul", "ol"}]
    direct_headings = [
        child for child in tag.children
        if isinstance(child, Tag) and (
            child.name in {"h1", "h2", "h3", "h4", "h5", "h6"}
            or is_nav_heading_tag(child)
        )
    ]
    if direct_headings:
        return True
    if len(direct_lists) >= 2:
        return True
   
    shallow_headings = 0
    for child in tag.find_all(True, recursive=False):
        if child.name in {"ul", "ol"}:
            continue
        if child.find(["h1", "h2", "h3", "h4", "h5", "h6"], recursive=False):
            shallow_headings += 1
    return shallow_headings > 0


def url_path_in_prefix(url: str, site_prefix: Optional[str]) -> bool:
    if not site_prefix:
        return True
    prefix = ensure_trailing_slash(site_prefix)
    if prefix == "/":
        return True
    return urlsplit(url).path.startswith(prefix)


def select_nav_root(
    soup: BeautifulSoup,
    current_domain: str,
    base_url: Optional[str] = None,
    content_root: Optional[Tag] = None,
    profile: str = "generic",
    current_url: Optional[str] = None,
    site_prefix: Optional[str] = None,
) -> Optional[Tag]:



    candidates: List[Tuple[int, int, int, int, Tag]] = []
    seen: Set[int] = set()
    selectors = profile_selectors(profile, "nav")

   
   
   
    broad_selectors = [
        "aside", "nav", "ul", "ol",
        "[id*='sidebar' i]", "[class*='sidebar' i]",
        "[id*='sidenav' i]", "[class*='sidenav' i]",
        "[id*='side-nav' i]", "[class*='side-nav' i]",
        "[id*='navcolumn' i]", "[id*='leftColumn' i]",
        "[class*='toc-tree' i]", "[class*='toctree' i]",
        "[class*='book-menu' i]", "[class*='gitbook' i]", "[class*='wy-menu' i]",
        "[class*='bd-sidebar' i]", "[class*='bd-links' i]",
        "[class*='md-sidebar' i]", "[class*='VPSidebar' i]", "[class*='VPSidebarNav' i]",
        "[data-testid*='sidebar' i]", "[data-testid*='navigation' i]",
        "[class*='menu__list' i]", "[class*='menu-list' i]",
    ]

    def consider(node: Tag) -> None:
        if id(node) in seen:
            return
        seen.add(id(node))
        score = compute_nav_score(
            node,
            current_domain=current_domain,
            base_url=base_url,
            content_root=content_root,
            current_url=normalize_url(current_url) if current_url else None,
            site_prefix=site_prefix,
            profile=profile,
            allow_javadoc=profile == "javadoc",
        )
        if score <= 0:
            return
        sidebar_bonus = 1 if is_sidebarish_tag(node) else 0
        global_penalty = 1 if is_inside_global_chrome(node) else 0
        text_len = len(clean_text(node.get_text(" ", strip=True)))
        candidates.append((score, sidebar_bonus, -global_penalty, -text_len, node))

    for selector in selectors:
        for node in soup.select(selector):
            consider(node)

   
   
   
    for selector in broad_selectors:
        for node in soup.select(selector):
            consider(node)

    if not candidates:
        return None

    candidates.sort(key=lambda item: (item[0], item[1], item[2], item[3]), reverse=True)

    best = candidates[0]
    best_node = best[4]
    best_score = best[0]

   
   
   
   
    if best_node.name in {"ul", "ol"}:
        for parent in best_node.parents:
            if not isinstance(parent, Tag) or parent.name in {"body", "html"}:
                break
            if not has_structured_nav_headings(parent):
                continue
            parent_score = compute_nav_score(
                parent,
                current_domain=current_domain,
                base_url=base_url,
                content_root=content_root,
                current_url=normalize_url(current_url) if current_url else None,
                site_prefix=site_prefix,
                profile=profile,
                allow_javadoc=profile == "javadoc",
            )
            if parent_score > 0 and (
                is_sidebarish_tag(parent)
                or parent_score >= int(best_score * 0.28)
            ):
                return parent

    if is_sidebarish_tag(best_node) and has_structured_nav_headings(best_node):
        return best_node

   
   
   
   
    if site_prefix and site_prefix != "/":
        best_scoped = 0
        best_depth = 0
        for a in best_node.select("a[href]"):
            href = (a.get("href") or "").strip()
            if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            abs_url = split_and_normalize(base_url or ("https://" + current_domain), href)[0]
            if url_path_in_prefix(abs_url, site_prefix):
                best_scoped += 1
        best_depth = len(best_node.find_all(["ul", "ol"]))
        for score, sidebar_bonus, global_penalty, _neg_text_len, node in candidates[1:]:
            scoped = 0
            for a in node.select("a[href]"):
                href = (a.get("href") or "").strip()
                if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
                    continue
                abs_url = split_and_normalize(base_url or ("https://" + current_domain), href)[0]
                if url_path_in_prefix(abs_url, site_prefix):
                    scoped += 1
            depth = len(node.find_all(["ul", "ol"]))
            if scoped >= max(6, best_scoped + 4) and depth >= best_depth and not is_inside_global_chrome(node):
                return node

   
   
   
    for score, sidebar_bonus, global_penalty, _neg_text_len, node in candidates[1:]:
        try:
            is_descendant = node in best_node.descendants
        except Exception:
            is_descendant = False
        if not is_descendant:
            continue
        if score >= int(best_score * 0.72) and (sidebar_bonus or not global_penalty):
            return node

    return best_node


def compute_nav_score(
    node: Tag,
    current_domain: str,
    base_url: Optional[str] = None,
    content_root: Optional[Tag] = None,
    current_url: Optional[str] = None,
    site_prefix: Optional[str] = None,
    profile: str = "generic",
    allow_javadoc: bool = False,
) -> int:
    internal_links: List[str] = []
    scoped_links: List[str] = []
    fragment_links = 0
    contains_current = False
    base = base_url or ("https://" + current_domain)

    for a in node.select("a[href]"):
        href = (a.get("href") or "").strip()
        if not href or href.startswith(("javascript:", "mailto:", "tel:")):
            continue
        if href.startswith("#"):
            fragment_links += 1
            continue
        abs_url = split_and_normalize(base, href)[0]
        parts = urlsplit(abs_url)
        if parts.netloc != current_domain:
            continue
        ext = Path(parts.path).suffix.lower()
        if ext and ext not in DOC_PAGE_EXTENSIONS:
            continue
        if query_looks_search_like(abs_url):
            continue
        if should_skip_crawl_url(
            abs_url,
            link_text=link_visible_text(a),
            profile=profile,
            allow_javadoc=allow_javadoc or profile == "javadoc",
        ):
            continue
        internal_links.append(abs_url)
        if url_path_in_prefix(abs_url, site_prefix):
            scoped_links.append(abs_url)
        if current_url is not None and urls_equivalent(abs_url, current_url):
            contains_current = True

    unique_internal = set(internal_links)
    unique_scoped = set(scoped_links)
    unique_links = len(unique_internal)
    scoped_count = len(unique_scoped)
    offscope_count = max(0, unique_links - scoped_count)

    if unique_links == 0 and fragment_links == 0:
        return -1

    text = clean_text(node.get_text(" ", strip=True)).lower()
    attrs = tag_attr_signature(node)
    context = tag_context_signature(node)
    nested_lists = len(node.find_all(["ul", "ol"]))

    global_chrome = is_inside_global_chrome(node)
    sidebarish = is_sidebarish_tag(node)
    toc_like = is_toc_like_tag(node)

   
    if unique_links < 2 and fragment_links >= 3:
        return -1

    score = scoped_count * 230
    score += offscope_count * 25
    score += nested_lists * 45
    score += min(fragment_links, 12) * 3

    if sidebarish:
        score += 1800
    elif SIDEBAR_CONTEXT_RE.search(attrs):
        score += 1000

    if contains_current:
        score += 3200

    if site_prefix and site_prefix != "/":
        if scoped_count:
            score += int(1000 * (scoped_count / max(unique_links, 1)))
        if offscope_count > scoped_count:
            score -= (offscope_count - scoped_count) * 140
        if scoped_count < 2 and offscope_count >= 3:
            score -= 1200

    if re.search(r"sidebar|nav|menu|toctree|book-menu|wy-menu|leftcolumn|navcolumn|toc-tree", attrs):
        score += 450

    if toc_like:
        score -= 2500

    if "on this page" in text or "table of contents" in text or "page contents" in text:
        score -= 1200

    if GLOBAL_CHROME_RE.search(attrs) or global_chrome:
        score -= 3200

   
   
    if re.search(r"footer|mega-?menu|site-?map|global-?nav|navbar|topbar", context):
        score -= 1600

    if content_root is not None:
        try:
           
           
           
            if getattr(content_root, "name", None) != "body":
                if node is content_root or node in content_root.descendants:
                    score -= 1500
        except Exception:
            pass

   
    text_len = len(text)
    if text_len > 6000 and site_prefix and site_prefix != "/" and scoped_count < max(3, unique_links // 2):
        score -= 1000

   
   
    title_words = {clean_text(child.get_text(" ", strip=True)).lower() for child in node.find_all(["h1", "h2", "h3", "h4", "h5", "strong"], recursive=False)}
    if title_words & GLOBAL_NAV_TITLE_HINTS and not sidebarish:
        score -= 700

    return score


def nav_internal_doc_link_count(
    node: Optional[Tag],
    domain: str,
    base_url: str,
    site_prefix: Optional[str],
    profile: str = "generic",
) -> int:
    if node is None:
        return 0
    urls: Set[str] = set()
    for a in node.select("a[href]"):
        href = (a.get("href") or "").strip()
        if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
            continue
        abs_url = split_and_normalize(base_url, href)[0]
        parts = urlsplit(abs_url)
        if parts.netloc != domain:
            continue
        if not url_path_in_prefix(abs_url, site_prefix):
            continue
        if Path(parts.path).suffix.lower() not in DOC_PAGE_EXTENSIONS:
            continue
        if query_looks_search_like(abs_url):
            continue
        if should_skip_crawl_url(
            abs_url,
            link_text=link_visible_text(a),
            profile=profile,
            allow_javadoc=profile == "javadoc",
        ):
            continue
        urls.add(abs_url)
    return len(urls)


def generic_nav_is_weak(
    nav_root: Optional[Tag],
    domain: str,
    base_url: str,
    current_url: Optional[str],
    site_prefix: Optional[str],
) -> bool:
    if nav_root is None:
        return True

    link_count = nav_internal_doc_link_count(nav_root, domain, base_url, site_prefix)
    nested_lists = len(nav_root.find_all(["ul", "ol"]))
    sidebarish = is_sidebarish_tag(nav_root)
    globalish = is_inside_global_chrome(nav_root)
    attrs = tag_context_signature(nav_root)

    if sidebarish and link_count >= 3:
        return False
    if current_url and any(
        urls_equivalent(split_and_normalize(base_url, a.get("href", ""))[0], current_url)
        for a in nav_root.select("a[href]")
        if (a.get("href") or "").strip() and not (a.get("href") or "").strip().startswith("#")
    ):
        return link_count < 3

   
   
   
    if globalish and not sidebarish:
        return True
    if GLOBAL_CHROME_RE.search(attrs) and not sidebarish:
        return True
    if link_count < 3:
        return True
    if nested_lists == 0 and not sidebarish and link_count < 8:
        return True
    return False


def is_doc_link_hub(
    node: Optional[Tag],
    domain: str,
    base_url: str,
    site_prefix: Optional[str],
) -> bool:
    if node is None:
        return False
    links: Set[str] = set()
    docish = 0
    for a in node.select("a[href]"):
        href = (a.get("href") or "").strip()
        if not href or href.startswith(("#", "javascript:", "mailto:", "tel:")):
            continue
        abs_url = split_and_normalize(base_url, href)[0]
        parts = urlsplit(abs_url)
        if parts.netloc != domain:
            continue
        if not url_path_in_prefix(abs_url, site_prefix):
            continue
        if Path(parts.path).suffix.lower() not in DOC_PAGE_EXTENSIONS:
            continue
        if query_looks_search_like(abs_url):
            continue
        if should_skip_crawl_url(abs_url, link_text=link_visible_text(a), profile="generic"):
            continue
        links.add(abs_url)
        text = link_visible_text(a)
        tokens = path_token_set(parts.path)
        if GENERIC_DOC_LINK_TEXT_RE.search(text) or tokens & DOC_LIKE_KEYWORDS:
            docish += 1
    if len(links) < 3:
        return False
    headings = len(node.find_all(re.compile(r"^h[1-6]$")))
    lists = len(node.find_all(["ul", "ol", "dl"]))
    paragraphs = len(node.find_all("p"))
    text_len = len(clean_text(node.get_text(" ", strip=True)))
    if headings == 0 and lists == 0:
        return False
    if docish >= 2:
        return True
    return paragraphs <= 3 and text_len <= 12000


def link_visible_text(a: Tag) -> str:
    pieces = [a.get_text(" ", strip=True)]
    for attr in ("aria-label", "title"):
        value = a.get(attr)
        if value:
            pieces.append(str(value))
    return clean_text(" ".join(pieces))


def path_token_set(path: str) -> Set[str]:
    tokens: Set[str] = set()
    for seg in path.strip("/").split("/"):
        seg = unquote(seg).lower()
        if not seg:
            continue
        stem = Path(seg).stem if Path(seg).suffix else seg
        for part in re.split(r"[-_ .]+", stem):
            if part:
                tokens.add(part)
        tokens.add(stem)
    return tokens


def is_same_or_child_section(candidate_path: str, current_path: str, site_prefix: str) -> bool:
    if candidate_path == current_path:
        return False
    if site_prefix and site_prefix != "/" and candidate_path.startswith(site_prefix):
        return True

    current_dir = ensure_trailing_slash(posixpath.dirname(current_path) or "/")
    if candidate_path.startswith(current_dir):
        return True

    current_parts = [p for p in current_path.strip("/").split("/") if p]
    candidate_parts = [p for p in candidate_path.strip("/").split("/") if p]
    if not current_parts or not candidate_parts:
        return False
   
    if current_parts[0] == candidate_parts[0]:
        return True
    if len(current_parts) > 1 and len(candidate_parts) > 1 and current_parts[:-1] == candidate_parts[:-1]:
        return True
    return False


def generic_content_link_score(
    abs_url: str,
    link_text: str,
    current_url: str,
    site_prefix: str,
) -> int:
    parts = urlsplit(abs_url)
    current_parts = urlsplit(current_url)
    path = parts.path or "/"
    current_path = current_parts.path or "/"
    tokens = path_token_set(path)
    rel = path[len(site_prefix):].lstrip("/") if path.startswith(site_prefix) else path.lstrip("/")

    if should_skip_crawl_url(abs_url, link_text=link_text, profile="generic"):
        return -9999
    if tokens & GENERIC_SKIP_PATH_TOKENS:
        return -9999
    if GENERIC_BAD_LINK_TEXT_RE.search(link_text):
        return -400

    score = 0
    if site_prefix and site_prefix != "/" and path.startswith(site_prefix):
        score += 4
    if is_same_or_child_section(path, current_path, site_prefix):
        score += 3
    if path_similarity(path, current_path) >= 0.2:
        score += 2

    lowered_text = link_text.casefold()
    if GENERIC_DOC_LINK_TEXT_RE.search(link_text):
        score += 3
    if any(token in DOC_LIKE_KEYWORDS for token in tokens):
        score += 3

    docish_extra = {
        "intro", "introduction", "overview", "install", "installation", "setup",
        "quickstart", "quick-start", "start", "usage", "use", "config",
        "configuration", "configure", "api", "cli", "sdk", "examples", "example",
        "tutorial", "tutorials", "reference", "guide", "guides", "manual",
        "build", "building", "subproject", "subprojects", "module", "modules",
        "component", "components", "platform", "platforms", "architecture", "security",
        "faq", "howto", "how-to", "concept", "concepts",
    }
    if tokens & docish_extra:
        score += 3

    if re.search(r"\b(?:next|previous|prev|continue|learn\s+more|read\s+more)\b", lowered_text):
        score += 2

   
   
    if site_prefix == "/":
        if not (GENERIC_DOC_LINK_TEXT_RE.search(link_text) or tokens & docish_extra or tokens & DOC_LIKE_KEYWORDS):
            score -= 3
        if path.count("/") > 4 and path_similarity(path, current_path) < 0.2:
            score -= 2

    if len(rel) > 180:
        score -= 2
    return score


def should_follow_generic_content_link(
    abs_url: str,
    link_text: str,
    current_url: str,
    site_prefix: str,
) -> bool:
    if is_probably_asset(abs_url):
        return False
    score = generic_content_link_score(abs_url, link_text, current_url, site_prefix)
    return score >= 3


def extract_title(soup: BeautifulSoup, root: Optional[Tag]) -> str:
    if root is not None:
        h1 = root.find(re.compile(r"^h1$"))
        if h1:
            text = clean_text(h1.get_text(" ", strip=True))
            if text:
                return text
    meta = soup.find("meta", attrs={"property": "og:title"})
    if meta and meta.get("content"):
        return clean_text(meta["content"])
    if soup.title and soup.title.string:
        return clean_text(soup.title.string)
    return "Untitled"


def is_doc_like_page(content_root: Optional[Tag], nav_root: Optional[Tag], score: int) -> bool:



    if content_root is None:
        return False
    if score >= 400:
        return True

    text_len = len(clean_text(content_root.get_text(" ", strip=True)))
    headings = len(content_root.find_all(re.compile(r"^h[1-6]$")))
    paragraphs = len(content_root.find_all("p"))
    code_blocks = len(content_root.find_all("pre"))
    tables = len(content_root.find_all("table"))

   
   
    if text_len >= 10 and headings >= 1 and (paragraphs >= 1 or code_blocks >= 1 or tables >= 1):
        return True
    if text_len >= 60 and headings >= 1 and len(content_root.find_all(["ul", "ol", "dl"])) >= 1:
        return True

    if nav_root is None:
        return False
    return text_len >= 120


def first_nonempty_attr(tag: Tag, names: Sequence[str]) -> str:
    for name in names:
        value = (tag.get(name) or "").strip()
        if value:
            if name == "srcset":
                first = value.split(",", 1)[0].strip().split(" ", 1)[0].strip()
                if first:
                    return first
            return value
    return ""


def is_nav_heading_tag(tag: Tag) -> bool:
    classes = " ".join(tag.get("class", [])).lower()
    role = str(tag.get("role", "")).lower()
    if tag.name in {"h1", "h2", "h3", "h4", "h5", "h6"}:
        return True
    if "nav-header" in classes or "nav_header" in classes:
        return True
    if "sidebar-heading" in classes or "sidebar-title" in classes or "menu-heading" in classes:
        return True
    if role in {"heading", "separator"} and clean_text(tag.get_text(" ", strip=True)):
        return True
   
    if tag.name in {"strong", "b"} and not tag.find("a", href=True):
        text = clean_text(tag.get_text(" ", strip=True))
        return bool(text and len(text) <= 140)
    return False


def extract_crawl_links(
    soup: BeautifulSoup,
    domain: str,
    site_prefix: str,
    base_url: str,
    profile: str,
    follow_content_links: bool = False,
    current_url: Optional[str] = None,
    preferred_language: str = PREFERRED_LANGUAGE_DEFAULT,
) -> List[str]:



    content_root = select_content_root(soup, profile=profile)
    nav_root = select_nav_root(
        soup,
        current_domain=domain,
        base_url=base_url,
        content_root=content_root,
        profile=profile,
        current_url=current_url,
        site_prefix=site_prefix,
    )

    nav_link_count = nav_internal_doc_link_count(nav_root, domain, base_url, site_prefix, profile=profile)
    nav_is_weak = (
        profile == "generic"
        and generic_nav_is_weak(
            nav_root,
            domain=domain,
            base_url=base_url,
            current_url=current_url,
            site_prefix=site_prefix,
        )
    )
    generator_content_fallback = profile in {"book", "sphinx", "vitepress", "asciidoctor", "antora"} and nav_link_count < 3
    content_link_hub = profile == "generic" and is_doc_link_hub(content_root, domain, base_url, site_prefix)

    containers: List[Tuple[Tag, str]] = []
    if nav_root is not None and not nav_is_weak:
        containers.append((nav_root, "nav"))

   
    for selector in [
        "nav.pagination-nav",
        "[rel='next']",
        "[rel='prev']",
        "a[aria-label*='next' i]",
        "a[aria-label*='previous' i]",
        ".prev-next", ".pagination", ".pager",
    ]:
        for node in soup.select(selector):
            if isinstance(node, Tag):
                containers.append((node, "pagination"))

    auto_content_fallback = nav_is_weak or generator_content_fallback or content_link_hub

    if (follow_content_links or auto_content_fallback) and content_root is not None:
        containers.append((content_root, "content"))

   
   
   
    if not containers:
        if content_root is not None:
            containers.append((content_root, "content"))
        elif soup.body is not None:
            containers.append((soup.body, "content"))
        else:
            containers.append((soup, "content")) 

    out: List[str] = []
    seen: Set[str] = set()

    for container, source in containers:
        for a in container.select("a[href]"):
            href = (a.get("href") or "").strip()
            if not href:
                continue
            if href.startswith(("#", "javascript:", "mailto:", "tel:")):
                continue
            hreflang = str(a.get("hreflang") or "").strip()
            if hreflang and not language_matches_preference(hreflang, preferred_language):
                continue

            abs_url, _frag = split_and_normalize(base_url, href)
            parts = urlsplit(abs_url)
            if parts.netloc != domain:
                continue
            if not parts.path.startswith(site_prefix):
                continue
            ext = Path(parts.path).suffix.lower()
            if ext not in DOC_PAGE_EXTENSIONS:
                continue
            if query_looks_search_like(abs_url):
                continue
            text_value = link_visible_text(a)
            if should_skip_crawl_url(abs_url, link_text=text_value, profile=profile):
                continue

            if source == "content" and profile == "generic":
                text = link_visible_text(a)
                if not should_follow_generic_content_link(
                    abs_url,
                    link_text=text,
                    current_url=current_url or base_url,
                    site_prefix=site_prefix,
                ):
                    continue

            if abs_url in seen:
                continue
            seen.add(abs_url)
            out.append(abs_url)

    for tag in soup.select("iframe[src], frame[src], embed[src], object[data]"):
        raw = str(tag.get("src") or tag.get("data") or "").strip()
        if not raw or raw.startswith(("#", "javascript:", "mailto:", "tel:")):
            continue
        abs_url, _frag = split_and_normalize(base_url, raw)
        parts = urlsplit(abs_url)
        if parts.netloc != domain:
            continue
        if not parts.path.startswith(site_prefix):
            continue
        ext = Path(parts.path).suffix.lower()
        if ext not in DOC_PAGE_EXTENSIONS:
            continue
        if query_looks_search_like(abs_url):
            continue
        if should_skip_crawl_url(abs_url, profile=profile):
            continue

        if abs_url in seen:
            continue
        seen.add(abs_url)
        out.append(abs_url)

    return out

